name: weather_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^8.2.0
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
  - images/
  #   - images/a_dot_ham.jpeg

fonts:
  - family: Spartan MB
    fonts:
      - asset: fonts/SpartanMB-Black.otf
        weight: 900
  - family: League Spartan
    fonts:
      - asset: fonts/LeagueSpartan-ExtraBold.ttf
        weight: 800